/** @file
 * @brief Audio/Video Remote control Protocol header.
 */
/*
 * Copyright (c) 2015-2016 Intel Corporation
 *
 * SPDX-License-Identifier: Apache-2.0
 */
#ifndef __BT_AVRCP_H
#define __BT_AVRCP_H
#ifdef __cplusplus
extern "C" {
#endif
enum {
	BT_AVRCP_PASS_THROUGH_PUSHED = 0,
	BT_AVRCP_PASS_THROUGH_RELEASED = 1,
};
enum {
	BT_AVRCP_CMD_STATE_PASS_THROUGH_PUSHED = 0,
	BT_AVRCP_CMD_STATE_PASS_THROUGH_RELEASED = 1,
	BT_AVRCP_RSP_STATE_PASS_THROUGH_PUSHED = 0x80,
	BT_AVRCP_RSP_STATE_PASS_THROUGH_RELEASED = 0x81,
};
typedef enum {
	AVRCP_OPERATION_ID_SELECT = 0x00,
	AVRCP_OPERATION_ID_UP = 0x01,
	AVRCP_OPERATION_ID_DOWN = 0x02,
	AVRCP_OPERATION_ID_LEFT = 0x03,
	AVRCP_OPERATION_ID_RIGHT = 0x04,
	AVRCP_OPERATION_ID_RIGHT_UP = 0x05,
	AVRCP_OPERATION_ID_RIGHT_DOWN = 0x06,
	AVRCP_OPERATION_ID_LEFT_UP = 0x07,
	AVRCP_OPERATION_ID_LEFT_DOWN = 0x08,
	AVRCP_OPERATION_ID_ROOT_MENU = 0x09,
	AVRCP_OPERATION_ID_SETUP_MENU = 0x0A,
	AVRCP_OPERATION_ID_CONTENTS_MENU = 0x0B,
	AVRCP_OPERATION_ID_FAVORITE_MENU = 0x0C,
	AVRCP_OPERATION_ID_EXIT = 0x0D,
	AVRCP_OPERATION_ID_0 = 0x20,
	AVRCP_OPERATION_ID_1 = 0x21,
	AVRCP_OPERATION_ID_2 = 0x22,
	AVRCP_OPERATION_ID_3 = 0x23,
	AVRCP_OPERATION_ID_4 = 0x24,
	AVRCP_OPERATION_ID_5 = 0x25,
	AVRCP_OPERATION_ID_6 = 0x26,
	AVRCP_OPERATION_ID_7 = 0x27,
	AVRCP_OPERATION_ID_8 = 0x28,
	AVRCP_OPERATION_ID_9 = 0x29,
	AVRCP_OPERATION_ID_DOT = 0x2A,
	AVRCP_OPERATION_ID_ENTER = 0x2B,
	AVRCP_OPERATION_ID_CLEAR = 0x2C,
	AVRCP_OPERATION_ID_CHANNEL_UP = 0x30,
	AVRCP_OPERATION_ID_CHANNEL_DOWN = 0x31,
	AVRCP_OPERATION_ID_PREVIOUS_CHANNEL = 0x32,
	AVRCP_OPERATION_ID_SOUND_SELECT = 0x33,
	AVRCP_OPERATION_ID_INPUT_SELECT = 0x34,
	AVRCP_OPERATION_ID_DISPLAY_INFO = 0x35,
	AVRCP_OPERATION_ID_HELP = 0x36,
	AVRCP_OPERATION_ID_PAGE_UP = 0x37,
	AVRCP_OPERATION_ID_PAGE_DOWN = 0x38,
	AVRCP_OPERATION_ID_SKIP = 0x3C,
	AVRCP_OPERATION_ID_POWER = 0x40,
	AVRCP_OPERATION_ID_VOLUME_UP = 0x41,
	AVRCP_OPERATION_ID_VOLUME_DOWN = 0x42,
	AVRCP_OPERATION_ID_MUTE = 0x43,
	AVRCP_OPERATION_ID_PLAY = 0x44,
	AVRCP_OPERATION_ID_STOP = 0x45,
	AVRCP_OPERATION_ID_PAUSE = 0x46,
	AVRCP_OPERATION_ID_RECORD = 0x47,
	AVRCP_OPERATION_ID_REWIND = 0x48,
	AVRCP_OPERATION_ID_FAST_FORWARD = 0x49,
	AVRCP_OPERATION_ID_EJECT = 0x4A,
	AVRCP_OPERATION_ID_FORWARD = 0x4B,
	AVRCP_OPERATION_ID_BACKWARD = 0x4C,
	AVRCP_OPERATION_ID_ANGLE = 0x50,
	AVRCP_OPERATION_ID_SUBPICTURE = 0x51,
	AVRCP_OPERATION_ID_F1 = 0x71,
	AVRCP_OPERATION_ID_F2 = 0x72,
	AVRCP_OPERATION_ID_F3 = 0x73,
	AVRCP_OPERATION_ID_F4 = 0x74,
	AVRCP_OPERATION_ID_F5 = 0x75,
	AVRCP_OPERATION_ID_VENDOR_UNIQUE = 0x7E,
	AVRCP_OPERATION_ID_UNDEFINED = 0xFF
} avrcp_op_id;
enum {
	BT_AVRCP_EVENT_PLAYBACK_STATUS_CHANGED = 0x01,
	BT_AVRCP_EVENT_TRACK_CHANGED = 0x02,
	BT_AVRCP_EVENT_TRACK_REACHED_END = 0x03,
	BT_AVRCP_EVENT_TRACK_REACHED_START = 0x04,
	BT_AVRCP_EVENT_PLAYBACK_POS_CHANGED = 0x05,
	BT_AVRCP_EVENT_BATT_STATUS_CHANGED = 0x06,
	BT_AVRCP_EVENT_SYSTEM_STATUS_CHANGED = 0x07,
	BT_AVRCP_EVENT_PLAYER_APPLICATION_SETTING_CHANGED = 0x08,
	BT_AVRCP_EVENT_NOW_PLAYING_CONTENT_CHANGED = 0x09,
	BT_AVRCP_EVENT_AVAILABLE_PLAYERS_CHANGED = 0x0a,
	BT_AVRCP_EVENT_ADDRESSED_PLAYER_CHANGED = 0x0b,
	BT_AVRCP_EVENT_UIDS_CHANGED = 0x0c,
	BT_AVRCP_EVENT_VOLUME_CHANGED = 0x0d,
};
enum {
	BT_AVRCP_PLAYBACK_STATUS_STOPPED = 0x00,
	BT_AVRCP_PLAYBACK_STATUS_PLAYING = 0x01,
	BT_AVRCP_PLAYBACK_STATUS_PAUSED = 0x02,
	BT_AVRCP_PLAYBACK_STATUS_FWD_SEEK = 0x03,
	BT_AVRCP_PLAYBACK_STATUS_REV_SEEK = 0x04,
	BT_AVRCP_PLAYBACK_STATUS_ERROR = 0xFF,
};
enum {
	BT_AVRCP_ATTRIBUTE_ID_TITLE  = 0x01,
	BT_AVRCP_ATTRIBUTE_ID_ARTIST = 0x02,
	BT_AVRCP_ATTRIBUTE_ID_ALBUM  = 0x03,
	BT_AVRCP_ATTRIBUTE_ID_GENRE  = 0x06,
	BT_AVRCP_ATTRIBUTE_ID_TIME   = 0x07,
};
struct attribute_info{
	uint32_t id;
	uint16_t character_id;
	uint16_t len;
	uint8_t* data;
}__packed;
#define TOTAL_ATTRIBUTE_ITEM_NUM   5
struct id3_info{
	struct attribute_info item[TOTAL_ATTRIBUTE_ITEM_NUM];
}__packed;
#ifdef __cplusplus
}
#endif
#endif /* __BT_AVRCP_H */